version: '3.7'

services:
  backend:
    build:
      context: ./automated-internships-backend
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        pip install -e .
        uvicorn automated_internships.core.main:app --reload --workers 1 --host 0.0.0.0 --port 5001
    volumes:
      - ./automated-internships-backend/:/code/
    ports:
      - "5001"
    depends_on:
      - db
    env_file:
      - ./automated-internships-backend/env/web.env

  frontend:
    build: ./automated-internships-front
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        elm-app build
        serve -s build
    volumes:
      - ./automated-internships-front/automated-internships-front:/app/
    ports:
      - "5000"

  db:
    image: postgres:13
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./automated-internships-backend/env/db.env

  nginx:
    image: nginx:1.15-alpine
    depends_on:
      - backend
    ports:
      - "8000:8000"
    volumes:
      - ./nginx:/etc/nginx/conf.d

volumes:
  postgres_data:
